// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYTnlxr727z_x6hMgCuLAiSizSAPvQLt4',
    appId: '1:210332625155:web:5c9d56fa93acd3119ba136',
    messagingSenderId: '210332625155',
    projectId: 'electronics-c224e',
    authDomain: 'electronics-c224e.firebaseapp.com',
    storageBucket: 'electronics-c224e.firebasestorage.app',
    measurementId: 'G-RTLVC2DTQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6TOS1xmhlBOOn_rN8S6z69dEYxJ5CjIM',
    appId: '1:210332625155:android:395398e630feb8479ba136',
    messagingSenderId: '210332625155',
    projectId: 'electronics-c224e',
    storageBucket: 'electronics-c224e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2BO21y_QQkcMSebjNJhXrsfPTmAI4DAI',
    appId: '1:210332625155:ios:ba05f220eec5bc629ba136',
    messagingSenderId: '210332625155',
    projectId: 'electronics-c224e',
    storageBucket: 'electronics-c224e.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2BO21y_QQkcMSebjNJhXrsfPTmAI4DAI',
    appId: '1:210332625155:ios:ba05f220eec5bc629ba136',
    messagingSenderId: '210332625155',
    projectId: 'electronics-c224e',
    storageBucket: 'electronics-c224e.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYTnlxr727z_x6hMgCuLAiSizSAPvQLt4',
    appId: '1:210332625155:web:3a0c7d3bf5477f4a9ba136',
    messagingSenderId: '210332625155',
    projectId: 'electronics-c224e',
    authDomain: 'electronics-c224e.firebaseapp.com',
    storageBucket: 'electronics-c224e.firebasestorage.app',
    measurementId: 'G-EGRMBJCWEE',
  );
}
